/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TunnelsRouteImport } from './routes/tunnels'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiInternalUnregisterTunnelRouteImport } from './routes/api/internal/unregister-tunnel'
import { Route as ApiInternalRegisterTunnelRouteImport } from './routes/api/internal/register-tunnel'
import { Route as ApiInternalGenerateCodeRouteImport } from './routes/api/internal/generate-code'
import { Route as ApiInternalCheckCodeRouteImport } from './routes/api/internal/check-code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TunnelsRoute = TunnelsRouteImport.update({
  id: '/tunnels',
  path: '/tunnels',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalUnregisterTunnelRoute =
  ApiInternalUnregisterTunnelRouteImport.update({
    id: '/api/internal/unregister-tunnel',
    path: '/api/internal/unregister-tunnel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalRegisterTunnelRoute =
  ApiInternalRegisterTunnelRouteImport.update({
    id: '/api/internal/register-tunnel',
    path: '/api/internal/register-tunnel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalGenerateCodeRoute = ApiInternalGenerateCodeRouteImport.update({
  id: '/api/internal/generate-code',
  path: '/api/internal/generate-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalCheckCodeRoute = ApiInternalCheckCodeRouteImport.update({
  id: '/api/internal/check-code',
  path: '/api/internal/check-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/tunnels': typeof TunnelsRoute
  '/users': typeof UsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/check-code': typeof ApiInternalCheckCodeRoute
  '/api/internal/generate-code': typeof ApiInternalGenerateCodeRoute
  '/api/internal/register-tunnel': typeof ApiInternalRegisterTunnelRoute
  '/api/internal/unregister-tunnel': typeof ApiInternalUnregisterTunnelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/tunnels': typeof TunnelsRoute
  '/users': typeof UsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/check-code': typeof ApiInternalCheckCodeRoute
  '/api/internal/generate-code': typeof ApiInternalGenerateCodeRoute
  '/api/internal/register-tunnel': typeof ApiInternalRegisterTunnelRoute
  '/api/internal/unregister-tunnel': typeof ApiInternalUnregisterTunnelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/tunnels': typeof TunnelsRoute
  '/users': typeof UsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/check-code': typeof ApiInternalCheckCodeRoute
  '/api/internal/generate-code': typeof ApiInternalGenerateCodeRoute
  '/api/internal/register-tunnel': typeof ApiInternalRegisterTunnelRoute
  '/api/internal/unregister-tunnel': typeof ApiInternalUnregisterTunnelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/join'
    | '/login'
    | '/setup'
    | '/tunnels'
    | '/users'
    | '/api/auth/$'
    | '/api/internal/check-code'
    | '/api/internal/generate-code'
    | '/api/internal/register-tunnel'
    | '/api/internal/unregister-tunnel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/join'
    | '/login'
    | '/setup'
    | '/tunnels'
    | '/users'
    | '/api/auth/$'
    | '/api/internal/check-code'
    | '/api/internal/generate-code'
    | '/api/internal/register-tunnel'
    | '/api/internal/unregister-tunnel'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/join'
    | '/login'
    | '/setup'
    | '/tunnels'
    | '/users'
    | '/api/auth/$'
    | '/api/internal/check-code'
    | '/api/internal/generate-code'
    | '/api/internal/register-tunnel'
    | '/api/internal/unregister-tunnel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  TunnelsRoute: typeof TunnelsRoute
  UsersRoute: typeof UsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInternalCheckCodeRoute: typeof ApiInternalCheckCodeRoute
  ApiInternalGenerateCodeRoute: typeof ApiInternalGenerateCodeRoute
  ApiInternalRegisterTunnelRoute: typeof ApiInternalRegisterTunnelRoute
  ApiInternalUnregisterTunnelRoute: typeof ApiInternalUnregisterTunnelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tunnels': {
      id: '/tunnels'
      path: '/tunnels'
      fullPath: '/tunnels'
      preLoaderRoute: typeof TunnelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/unregister-tunnel': {
      id: '/api/internal/unregister-tunnel'
      path: '/api/internal/unregister-tunnel'
      fullPath: '/api/internal/unregister-tunnel'
      preLoaderRoute: typeof ApiInternalUnregisterTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/register-tunnel': {
      id: '/api/internal/register-tunnel'
      path: '/api/internal/register-tunnel'
      fullPath: '/api/internal/register-tunnel'
      preLoaderRoute: typeof ApiInternalRegisterTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/generate-code': {
      id: '/api/internal/generate-code'
      path: '/api/internal/generate-code'
      fullPath: '/api/internal/generate-code'
      preLoaderRoute: typeof ApiInternalGenerateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/check-code': {
      id: '/api/internal/check-code'
      path: '/api/internal/check-code'
      fullPath: '/api/internal/check-code'
      preLoaderRoute: typeof ApiInternalCheckCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  TunnelsRoute: TunnelsRoute,
  UsersRoute: UsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInternalCheckCodeRoute: ApiInternalCheckCodeRoute,
  ApiInternalGenerateCodeRoute: ApiInternalGenerateCodeRoute,
  ApiInternalRegisterTunnelRoute: ApiInternalRegisterTunnelRoute,
  ApiInternalUnregisterTunnelRoute: ApiInternalUnregisterTunnelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
