/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiInternalGenerateCodeRouteImport } from './routes/api/internal/generate-code'
import { Route as ApiInternalCheckCodeRouteImport } from './routes/api/internal/check-code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalGenerateCodeRoute = ApiInternalGenerateCodeRouteImport.update({
  id: '/api/internal/generate-code',
  path: '/api/internal/generate-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalCheckCodeRoute = ApiInternalCheckCodeRouteImport.update({
  id: '/api/internal/check-code',
  path: '/api/internal/check-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/check-code': typeof ApiInternalCheckCodeRoute
  '/api/internal/generate-code': typeof ApiInternalGenerateCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/check-code': typeof ApiInternalCheckCodeRoute
  '/api/internal/generate-code': typeof ApiInternalGenerateCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/check-code': typeof ApiInternalCheckCodeRoute
  '/api/internal/generate-code': typeof ApiInternalGenerateCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/dashboard'
    | '/login'
    | '/api/auth/$'
    | '/api/internal/check-code'
    | '/api/internal/generate-code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/dashboard'
    | '/login'
    | '/api/auth/$'
    | '/api/internal/check-code'
    | '/api/internal/generate-code'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/dashboard'
    | '/login'
    | '/api/auth/$'
    | '/api/internal/check-code'
    | '/api/internal/generate-code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInternalCheckCodeRoute: typeof ApiInternalCheckCodeRoute
  ApiInternalGenerateCodeRoute: typeof ApiInternalGenerateCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/generate-code': {
      id: '/api/internal/generate-code'
      path: '/api/internal/generate-code'
      fullPath: '/api/internal/generate-code'
      preLoaderRoute: typeof ApiInternalGenerateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/check-code': {
      id: '/api/internal/check-code'
      path: '/api/internal/check-code'
      fullPath: '/api/internal/check-code'
      preLoaderRoute: typeof ApiInternalCheckCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInternalCheckCodeRoute: ApiInternalCheckCodeRoute,
  ApiInternalGenerateCodeRoute: ApiInternalGenerateCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
